- name: Stopping iptables service
  systemd:
    name: iptables
    masked: true

- name: Uninstalling ufw
  apt:
    name: ufw
    state: absent

- name: Install firewalld
  apt:
    name: firewalld

- name: Checking firewalld service
  shell: |
    sudo systemctl status firewalld

- name: Start Firewalld & enable
  systemd:
    name: firewalld
    enabled: true

- name: Permiting SSH
  firewalld:
    service: ssh
    permanent: true
    state: enabled

- name: Permiting HTTP
  firewalld:
    service: http
    permanent: true
    state: enabled

- name: Permiting HTTPS
  firewalld:
    service: https
    permanent: true
    state: enabled

- block:
  - name: Checking Status
    command: systemctl status firewalld
    register: firewalld_service

  - debug:
       msg="{{ firewalld_service }}"

  - name: Checking Status
    command: firewall-cmd --list-services
    register: allowed_services

  - debug:
      msg="{{ allowed_services }}"


